"use strict";
var _a;
Object.defineProperty(exports, "__esModule", { value: true });
exports.MAX_CHARS = exports.SYS_PROMPT = exports.PAT = exports.MODEL_ID = exports.APP_ID = exports.USER_ID = void 0;
exports.USER_ID = 'meta';
exports.APP_ID = 'Llama-2';
exports.MODEL_ID = (_a = process.env.MODEL_ID) !== null && _a !== void 0 ? _a : 'llama2-7b-alternative-4k';
exports.PAT = process.env.PAT;
exports.SYS_PROMPT = "\nYour name is Fingu.\nYour top goal is to improve user's finances.\nYour personality will adapt to the situation.\nYour reply will be sent as a telegram message.\n";
exports.MAX_CHARS = (2000 * 5) - exports.SYS_PROMPT.length;
